version: '3.8'

# Pandacea Protocol Local Development Environment
# This compose file sets up a complete local development environment with all
# necessary services for testing and development of the Pandacea Protocol.

services:
  # Agent Backend Service - Core P2P node and HTTP API server
  # Provides data product discovery, policy evaluation, and P2P networking
  agent-backend:
    build:
      context: ./agent-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
      - P2P_LISTEN_PORT=0
    volumes:
      - ./agent-backend:/app
      - go-modules:/go/pkg/mod
    networks:
      - pandacea-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"   # gRPC
      - "4318:4318"   # HTTP
    networks:
      - pandacea-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9091:9090"
    networks:
      - pandacea-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - pandacea-network
    restart: unless-stopped

  # Anvil Blockchain Node - Local Ethereum development chain
  # Provides a local blockchain for smart contract testing and development
  # Includes pre-funded accounts and instant mining for rapid iteration
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil --host 0.0.0.0 --port 8545
    ports:
      - "8545:8545"
    volumes:
      - anvil-data:/root/.anvil
    networks:
      - pandacea-network
    restart: unless-stopped

  # IPFS Node - Distributed file system for P2P content addressing
  # Enables decentralized storage and content discovery for the protocol
  # Provides DHT (Distributed Hash Table) functionality for peer discovery
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "4001:4001"
      - "5001:5001"
      - "9090:8080"
    volumes:
      - ipfs-data:/data/ipfs
    networks:
      - pandacea-network
    restart: unless-stopped

  chaos-monkey:
    image: alpine:latest
    container_name: chaos-monkey
    depends_on:
      - agent-backend
    volumes:
      - ./integration:/integration
    entrypoint: ["/bin/sh", "/integration/chaos_test.sh"]
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: unless-stopped
    # This service intentionally disrupts agent-backend for chaos testing

  # PySyft Datasite Service - Privacy-preserving computation environment
  # Provides isolated containers for executing federated learning and other
  # privacy-preserving computations using OpenMined's PySyft
  pysyft-datasite:
    build:
      context: ./agent-backend
      dockerfile: Dockerfile.pysyft
    image: pandacea/pysyft-datasite:latest
    container_name: pysyft-datasite
    networks:
      - pandacea-network
    # This service is used by the agent-backend for privacy-preserving computations
    # It's not started by default but built and available when needed

volumes:
  # Go modules cache - Persists Go module dependencies between container restarts
  # Improves build performance and reduces network usage
  go-modules:
  # Anvil blockchain data - Persists blockchain state between sessions
  # Allows for consistent testing environment and contract deployment history
  anvil-data:
  # IPFS data - Persists IPFS node data and content addressing information
  # Maintains distributed content and peer discovery state
  ipfs-data:
  grafana-data:

networks:
  pandacea-network:
    driver: bridge 