global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'agent-backend'
    static_configs:
      - targets: ['agent-backend:8080']
    metrics_path: /metrics

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

