name: Agent Backend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'agent-backend/**'
      - '.github/workflows/agent-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'agent-backend/**'
      - '.github/workflows/agent-ci.yml'

jobs:
  test:
    name: Test and Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
        
    - name: Install dependencies
      working-directory: agent-backend
      run: go mod download
      
    - name: Run unit tests
      working-directory: agent-backend
      run: go test -v ./...
      
    - name: Install gosec
      run: |
        curl -sfL https://raw.githubusercontent.com/securecodewarrior/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.18.2
        
    - name: Run security scan
      working-directory: agent-backend
      run: |
        gosec -fmt=json -out=security-report.json -config=.gosec ./...
        gosec -fmt=text -config=.gosec ./...
      continue-on-error: false
      
    - name: Check for security issues
      working-directory: agent-backend
      run: |
        # Parse gosec output and fail if medium or high severity issues found
        if [ -f security-report.json ]; then
          # Count medium and high severity issues
          MEDIUM_HIGH_COUNT=$(jq -r '.Issues[] | select(.severity == "MEDIUM" or .severity == "HIGH") | .severity' security-report.json | wc -l)
          
          if [ "$MEDIUM_HIGH_COUNT" -gt 0 ]; then
            echo "❌ Found $MEDIUM_HIGH_COUNT medium or high severity security issues"
            echo "Security scan failed. Please review and fix the issues above."
            exit 1
          else
            echo "✅ No medium or high severity security issues found"
          fi
        else
          echo "❌ Security report not generated"
          exit 1
        fi
        
    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: agent-backend/security-report.json
        retention-days: 30 